name: tootle
version: git
summary: Tootle
description: |
  Tootle is a client for the world’s largest free, open-source, decentralized 
  microblogging network with real-time notifications and multiple accounts 
  support.

  Mastodon is lovely crafted with power and speed in mind, resulting in a 
  free, independent and popular alternative to the centralized social 
  networks.

  Anyone can run a server of Mastodon. Each server hosts individual user 
  accounts, the content they produce, and the content they are subscribed. 
  Every user can follow each other and share their posts regardless of 
  their server.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  tootle:
    interface: dbus
    bus: session
    name: com.github.bleakgrey.tootle

apps:
  tootle:
    command: bin/desktop-launch ${SNAP}/usr/bin/com.github.bleakgrey.tootle
    desktop: usr/share/applications/com.github.bleakgrey.tootle.desktop
    plugs:
      - desktop
      - desktop-legacy
      - home
      - gsettings
      - network
      - wayland
      - x11
      - unity7

parts:
  elementary:
    plugin: nil
    override-build: |
      apt-get -y update
      apt-get install -y software-properties-common
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      add-apt-repository -y ppa:elementary-os/stable
      apt-get -y update
      apt-get -y dist-upgrade
  desktop-gnome-platform:
    after: [elementary]
  tootle:
    build-attributes: ['no-system-libraries']
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    override-build: |
      sed -i.bak -e 's|Icon=com.github.bleakgrey.tootle$|Icon=${SNAP}/meta/gui/tootle.png|g' data/com.github.bleakgrey.tootle.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters:
      - --prefix=/snap/tootle/current/usr
    organize:
      snap/tootle/current/usr: usr
    build-packages:
      - valac
      - libgranite-dev
      - libgtk-3-dev
      - libglib2.0-dev
      - libsoup2.4-dev
      - libjson-glib-dev
    stage-packages:
      - libgranite4
      - libjson-glib-1.0-0
      - libsoup2.4-1
